### ISSUE TITLE
Photos / Videos missing ? 

### ISSUE THREAD

**Issue by Zazou49** [boredazfcuk/docker-icloudpd#104]
Hey,

I noticed there was a difference of 65 files (minus .mounted file) between iCloud and the backup. I checked the log but I didn't find any particular warning message. How can I know what is missing ?

![Capture d’écran 2021-09-19 144712](https://user-images.githubusercontent.com/89610869/133928029-d66687a5-a407-4ef0-919f-041bac531537.png)
28835 vs 28900

```
2021-09-19 14:04:43 INFO All photos have been downloaded!
2021-09-19 14:04:43 INFO Synchronisation complete for user
2021-09-19 14:04:43 INFO Web cookie expires: 2021-11-17 @ 23:24:54
2021-09-19 14:04:43 INFO Two factor authentication cookie expires: 2021-12-17 @ 23:25:05
2021-09-19 14:04:43 INFO Days remaining until expiration: 89
2021-09-19 14:04:43 INFO iCloud login counter = 4
2021-09-19 14:04:43 INFO Synchronisation ended at 14:04:43
2021-09-19 14:04:43 INFO Total time taken: 00:38:55
2021-09-19 14:04:43 INFO Next synchronisation at 01:25:48
```

**Comment by boredazfcuk** [comment]
Hi,

This will most likely be down to how Apple devices handle certain types of photos.

For example, photos that have been edited are stored as two separate files, the original unedited HEIC file, and then a metadata file (a .AEE file) which contains the edit (like a crop, or pencil drawn over the top, filter etc). This why you can always undo any changes you made, because those changes are not made to the original file. 

I believe all “portrait” photos are just a standard photo and then an edit file to accompany it.

When a Mac/iPhone counts the files, it also counts the edits. So if you have files with multiple edits, it will count each edit as a separate photo. In the cloud, you only have a single .HEIC file though. 

Unfortunately, the icloudpd Python app does not support downloading the edit files (at the moment, there has been an issue raised and I believe people are looking into ways of saving the edits). So when you see the file count when looking at your file system, it is only counting the number of underlying base image files (.HEIC, .JPG, .PNG etc).

As far as I’m aware, there’s no way of telling which files have edits, at the moment.

There’s also an issue with the option which sets EXIF data from the time stamp. This can lead to multiple files existing for a single cloud file, as setting the EXIF data changes the downloaded file, so on the subsequent run, the file is downloaded a second time.

Hopefully these issue are addressed in future versions of the underlying application, but if I’m being honest, development in it has been a little slow of late.

**Comment by Zazou49** [comment]
Hi @boredazfcuk,

Thank you for this very detailed answer, I am reassured! No worries for the development of the application, I think it fulfills 99% of the expectations of the people that they use it!

**Comment by boredazfcuk** [comment]
Yeah, for me it's just that reassurance that I've got a backup (well, four backups if we're counting).

In other news, it looks like there may be rumblings on the development front though. Watch this space!

**Comment by boredazfcuk** [comment]
Just closing this off as there's nothing further I can really add.
