### ISSUE TITLE
F2A alert at each sync.

### ISSUE THREAD

**Issue by Zazou49** [boredazfcuk/docker-icloudpd#106]
I'm sorry to open a ticket again, but new error for me. 

Since few updates (2 or 3), each time sync happens, I can see in log the F2A request. I have alert on my iPhone too.

![image](https://user-images.githubusercontent.com/89610869/134416149-af8b38ba-be27-449d-ae24-3cb3b30e6ae8.png)

**Comment by boredazfcuk** [comment]
Have you changed your Apple ID password recently? That could be causing the authentication failure.

Can you connect to the container (assuming it's called icloudpd) with:
```
docker exec -it icloudpd /bin/ash
```
Then run `/usr/local/sbin/sync-icloud.sh` and go through the authentication process manually? It's probably aborting because it's recognising that there's no console available to the container, so the password cannot be entered.

**Comment by Zazou49** [comment]
No I have the same Apple ID password recently for months now. 

I tried to execute manually the command but I think something is wrong :D 

![image](https://user-images.githubusercontent.com/89610869/134425087-36d3d4b0-5e6f-4b6a-8d4b-8e8e6966fa00.png)

**Comment by boredazfcuk** [comment]
Sorry, my bad. The script store on my Debian host is `/usr/local/sbin` but that location doesn't exist in Alpine Linux which runs inside the container. I mix them up sometimes.

The correct path is: `/usr/local/bin/sync-icloud.sh`

**Comment by Zazou49** [comment]
Worked ! Time to see tomorrow when the next sync happens ! Thank you for your support !

**Comment by boredazfcuk** [comment]
Great news. Hopefully it'll settle down for a while now.
