### ISSUE TITLE
App Specific Apple ID password

### ISSUE THREAD

**Issue by gregbert42** [boredazfcuk/docker-icloudpd#118]
I had this working with 2FA
However, I tried to set an app specific password with apple, and set my authentication to web.
this doesnt seem to work - says i have the wrong password.

Should this work? or is there a reason this shouldnt work.

**Comment by boredazfcuk** [comment]
> Should this work? 

In short, no.

> is there a reason this shouldnt work.

The underlying application logs on to icloud.com and then pulls the photos down by interacting with the web UI. App-specific passwords can't be used to log on to icloud.com, which is why you're getting "wrong password".

Also, app-specific passwords don't have access photo data. They can only be used to synchronise mail, contacts and calendar services. Even if the underlying app could be modified to use an app-specific password, it would lose access to the photo data, so it's not a feature that could even be developed.
