### ISSUE TITLE
ERROR Destination volume not mounted (Docker/unraid)

### ISSUE THREAD

**Issue by pairofcrocs** [boredazfcuk/docker-icloudpd#13]
I see in the docker readme that it requires either a "named volume mapped to /config" or ".mounted" file in /home/${user}/iCloud. I'm confused on what this means? 

Any information would be very helpful!

Thanks :)

**Comment by boredazfcuk** [comment]
Hi,

I think you may be misunderstanding. These are two unrelated aspects. 

The container stores the 2-Factor Authentication cookie in the /config folder. If the volume is not named, then the volume is at risk of being deleted whenever the container is recreated. This isn't a massive issue, as you can just re-authenticate, but it just means manual intervention. It will be bigger problem if your containers auto-update on a schedule. however, if you don't have 2-factor authentication enabled on your Apple ID, then it's a non-issue and you can just ignore it.

The .mounted file is a fail safe mechanism and should be created on the docker host computer. The container looks for the file and will only proceed with the download if the file is present. That way, if the volume that your photos are stored on gets dismounted, the file will be missing and the container knows not to download files.

For example, I have my photos stored in the `/mnt/hd2/sync/boredazfcuk/iCloud/` directory on my computer and it is mapped to `/home/boredazfcuk/iCloud' inside the container. On the host machine, I then created the fail-safe file from a terminal window: `touch /mnt/hd2/sync/boredazfcuk/iCloud/.mounted`

When the container launches, it looks the `/home/boredazfcuk/iCloud/.mounted` file. If it's there, it continues with the download. If it isn't it quits out.

The reason I have it is because the disk drive I had my photos on failed and was dismounted. The container then re-downloaded GBs of photos from my iCloud and filled up the root volume.

**Comment by pairofcrocs** [comment]
Got it.

I added a .mounted file in my directory and am still getting the same error.
I posted about it on the unraid subreddit to see if anyone else was having the same issue and it seems that at least one other person was having the same problem.

Could this just be a miss configured template, or are we missing something else?

**Comment by pairofcrocs** [comment]
someone figured it out.

change "/home/user/icloud" to "/home/user/iCloud"

**Comment by boredazfcuk** [comment]
> I posted about it on the unraid subreddit to see if anyone else was having the same issue and it seems that at least one other person was having the same problem.

Sorry, I use this on a home built SAN and use Debian as the OS, so I'm not familiar with UNRAID. Somebody did say they were running it on a Synology NAS and that runs all containers interactively so they couldn't get past the 2FA prompt. I added a variable to accommodate this. If UNRAID has similar oddities, I should be able to work out what's happening and fix with a little help.

I've changed the error that's reported to `Failsafe file /home/${user}/iCloud/.mounted file is not present`
so that it's more specific and hopefully people will spot it more easily. Capitalisation in Linux makes a difference so I tend to stick to defaults. The iCloud capitalisation is a throwback to when I was syncing iCloud photos to my laptop using the Windows iCloud control panel which capitalises the C.
