### ISSUE TITLE
Pics are different from they are in iCloud

### ISSUE THREAD

**Issue by GeorgeUgly** [boredazfcuk/docker-icloudpd#145]
Hi,

Recently, I found that photos which is downloaded from icloudpd are different from what they are downloaded from iCloud.

1. the original pic is 16:9 in iCloud, but 4:3 in icloudpd
2. Filter effect of iPhone exists in iCloud, but removed in icloudpd

It likes icloudpd download an "Original" version of the photo.

is there any options or variable I can use to avoid these things?

**Comment by boredazfcuk** [comment]
Hi,

The photos iCloudPD downloads are identical to the files which are stored in iCloud though.

The issue is that a lot of the photos are presented differently depending on where they are viewed from.

For example, if you take a "Portrait" photo it will be stored in iCloud as a the base photo (a .HEIC file) and an after-effect (.AAE file). The after-effect file is a small XML file which tells the software (iOS or icloud.com website) which after-effect to apply to the photo when displaying it. In this case the "Portrait" after-effect.

When you look at that photo on your phone/tablet or in the cloud, the software will render the picture with the after-effect applied. The photo you see is a virtual photo. It doesn't exist on the phone/tablet or in the cloud, it is created in real time by the software.

The same is true if you browse the iPhone/iPad when it is plugged into your computer via the cable (at least on my windows laptop it does). If you take a "Portrait" photo, it will save that as a HEIC and an AAE file to the local storage, and sync those to the cloud. When you browse the iPhone from Windows Explorer however, it will present three files instead of one:
IMG_XXXX.JPG
IMG_XXXX.AAE
IMG_EXXXX.JPG

The two JPG files don't actually exist. They are both derived from the HEIC file that lives on your device. The IMG_XXXX.JPG file is a direct conversion where the IMG_EXXX.JPG is the combination of the HEIC with the .AAE transformation applied.

Unfortunately, the underlying application does not replicate the functionality of iOS or icloud.com by applying the transformations to the photos and storing them as an additional file.

That would need to be added as a feature to the underlying application, which I see you've already opened an issue for in the correct repo: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/412

If they add the capability to create the post-transformation photos from the original files, then I will be able to make that a configurable option within my container.

**Comment by GeorgeUgly** [comment]
Got it, thanks for your explanation
