### ISSUE TITLE
Apple Notification Mail

### ISSUE THREAD

**Issue by 404gods** [boredazfcuk/docker-icloudpd#151]
I have been using icloudpd for several months and it has been normal. Today, I suddenly received an email from Apple, informing me:
My Apple ID is logged into iCloud on a web browser, OS: linux .
Is it the reason icloudpd is working?

**Comment by boredazfcuk** [comment]
Hi,

I see these quite frequently as I synchronise four accounts with four different containers.

The underlying application interacts with the icloud.com website to download files. kind of like how a web browser does when you log into the site.

You're getting the message because icloud.com thinks you're logging in, when in reality it's the application authenticating to icloud.com to download the files. I've not paid much attention to when I've received these e-mails, I think they are generated when I save the password to the keyring, so basically each time you use the `--initialise` command line option.
