### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by eleaner** [boredazfcuk/docker-icloudpd#18]
Hi, when authenticating I am getting this weird error
please help
```

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.5.0', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.5.0-py3.8.egg/icloudpd/base.py", line 292, in main
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-08-02 12:55:25 INFO     Please ignore the 'expected str, bytes or os.PathLike object, not NoneType' error. This is a fault with the underlying application Python application
```

**Comment by boredazfcuk** [comment]
Hi,

That error is to be expected. The Python application which runs inside my container is generating the error. I'm not sure why it generates this error as I'm not a Python expert, but it doesn't seem to affect anything. That's why I add the:
```
INFO     Please ignore the 'expected str, bytes or os.PathLike object, not NoneType' error.
```
line to the log file.

**Comment by boredazfcuk** [comment]
Actually,..

I've just worked out why this issue is happening and amended the code to fix it.

New code has been built on Dockerhub and I've pushed new ARM/ARM64 images too.

If the problems remains, just update this issue and I'll take another look at it.

**Comment by eleaner** [comment]
thank you

**Comment by AndreyNikiforov** [comment]
> I've just worked out why this issue is happening and amended the code to fix it.
> 
@boredazfcuk What was the problem and how it was fixed?

Same issue reported https://github.com/ndbroadbent/icloud_photos_downloader/issues/175

**Comment by boredazfcuk** [comment]
The issue was due to me not specifying the `--directory` command, as I didn't know it was mandatory.

I created a function that had the sole purpose of generating a 2FA cookie (not performing the download) and the command that generated the cookie was basically:
```
/usr/bin/icloudpd --username "${0}" --password "${1}" --cookie-directory "${2}"
```
I expected this to generate the cookie and then exit. It partially worked, as it would create the cookie after completing the 2FA process, but then it would throw the error.

The next step was to generate my cookie like this:
```
/usr/bin/icloudpd --username "${0}" --password "${1}" --cookie-directory "${2}" --directory "/tmp/test" --only-print-filenames'
```
However, I found that icloudpd would actually create the full directory structure for my Photo Stream in /tmp/test... So like
```
/tmp/test
   |-2020
   |      |- 10
   |           |- 01
   |           |- 02
   |
   |- 2019
```
Which wasn't what I wanted.

The command then evolved into:
```
/usr/bin/icloudpd --username "${0}" --password "${1}" --cookie-directory "${2}" --directory "/dev/null" --only-print-filenames'
```
So that the empty file structure would just get thrown into the bit bucket.

The final version I settled on was actually this (I'm surprised it worked to be honest):
```
/usr/bin/icloudpd --username "${0}" --password "${1}" --cookie-directory "${2}" --directory "/dev/null" --only-print-filenames --recent 0'
```
Adding the `--recent 0` to the end sped it up a little, because it returned empty results each time anyway.
