### ISSUE TITLE
Begineer here : keyring ?

### ISSUE THREAD

**Issue by Galiwyx** [boredazfcuk/docker-icloudpd#20]
Hello,

I'm using unRAID as system. I want to use the keyring system but the command doesn't work "/usr/local/bin/sync-icloud.sh" (not found).

In my appdata folders, I have 3 files:
![image](https://user-images.githubusercontent.com/206181/89675677-a32fff00-d8ea-11ea-9a96-fb5a01279e8d.png)
python_keyring is empty.

thank you

**Comment by boredazfcuk** [comment]
Hi,

Unfortunately I'm unfamiliar with unRAID.

The command is:
```
docker exec -it icloudpd /usr/local/bin/sync-icloud.sh
```

and this would need to be run from a terminal prompt on your unRAID system. It tells Docker that it should connect to your icloudpd container and run the '/usr/local/bin/sync-icloud.sh' so that you can enter your credentials.

You could also run:
```
docker exec -it icloudpd /bin/ash
```
which will give you a terminal prompt inside the container. From there you can `cd /usr/local/bin' folder.

Alternatively, you can create a second, temporary, container which runs interactively and enter the credentials there. I've updated the READ.ME file with instructions on how to do this.

Let me know how you get on.

**Comment by Galiwyx** [comment]
Hello boredazfcuk !

Thank you for your detailed answer. I run the fist command and set the keyring ! Everything is working now. Thank you very very much !!! I have just an error but I don't think is a big issue:

![image](https://user-images.githubusercontent.com/206181/89690959-13994900-d908-11ea-9939-0b29c07bcb7e.png)

**Comment by boredazfcuk** [comment]
It's likely that this is an issue with the Python app that is installed in my container as it has issues with strange/empty album names.. See here:

https://github.com/ndbroadbent/icloud_photos_downloader/issues/150

Anyway, I've created a diff of the changes suggested to fix the issue (I think it will just make it skip the oddly named albums, I don't know for sure as I can't test) and apply this patch in a new build.

I've pushed a new version to Dockerhub and it should be good to go.

**Comment by boredazfcuk** [comment]
Just closing this off as I've not heard anything back in a week. Presumably, the path that's applied in the latest version fixed your problem. Just comment again if that's not the case and I'll reopen the issue.
