### ISSUE TITLE
how to re-initiliase after change password?

### ISSUE THREAD

**Issue by tokyoqiang** [boredazfcuk/docker-icloudpd#210]
Hi Dear,

can you let me know how to re-initialise after changed password? Thanks!

Step 1: tried to run command line:  docker exec -it iCloud_tokyoqiang-auto-index sync-icloud.sh --RemoveKeyring
Step 2: tried to run command line:  docker exec -it iCloud_tokyoqiang-auto-index sync-icloud.sh --Initialise

After step1, it shows
<img width="627" alt="result" src="https://user-images.githubusercontent.com/99979431/191314614-1362ad1d-7332-4e49-9def-62cf03ac39ce.png">
AFter step2, it shows
<img width="660" alt="docker exec -it iCloud_tokyoqiang-auto-index sync-icloud sh --Initialise" src="https://user-images.githubusercontent.com/99979431/191314851-cb55a689-efbc-4600-9b86-dea6e63f0013.png">

**Comment by boredazfcuk** [comment]
Pull the latest container version and run this command again, there was an issue with the launch parameter, preventing it from running correctly:
```
docker exec -it iCloud_tokyoqiang-auto-index sync-icloud.sh --RemoveKeyring
```

Also, log into your iCloud.com account and check you can log in OK. I just had the same error on my wife's account and it's because iCloud.com was prompting to upgrade to 2FA before it would let you get through to the main screen.

**Comment by tokyoqiang** [comment]
Thank you so much, boredazfcuk, you saved me!
Pulled the latest container version, then re-run your command, it works.
Thanks again for developing so great & useful app!
