### ISSUE TITLE
How to sync shared library?

### ISSUE THREAD

**Issue by Se7enair** [boredazfcuk/docker-icloudpd#231]
Its written `photo_library: Set this to the name of an iOS 16 shared library to only download photos from a single sared library.`
But how do I get the name of the shared library?

I tried `docker exec -it icloudpd sync-icloud.sh --list-libraries` but it does not work.

**Comment by leonardpitzu** [comment]
Same dilemma over here. I tried the "Shared Library" obvious name but did not work...

**Comment by zbare** [comment]
I got it to work using this:

`sudo docker exec -it {container_name} /usr/bin/icloudpd --list-libraries`

Once you enable shared libraries in iCloud, the output will show a library like SharedSync-{Unique ID#}

Based on the readme, and looking at the patch file also, it looks like you can either pull photos from the Personal Library (name: PrimarySync) or from the Shared Library (name: SharedSync-{Unique ID#}); Not both. So it seems that you will need two containers running if you want to pull from both libraries. More if you have personal libraries of other members of your iCloud account that you want to pull as well.

**Comment by Se7enair** [comment]
It is syncing, wonderful!
![Auswahl_015](https://user-images.githubusercontent.com/1680106/205156032-3f06c5d2-e58a-4c48-8445-eec9578dd618.png)

**Comment by boredazfcuk** [comment]
Hi,

Sorry for taking so long to look at this. Work has been mental these past few weeks.

Log now outputs a list of shared libraries:
```
2022-12-03 16:52:01 INFO     Shared libraries available:
2022-12-03 16:52:06 INFO      - PrimarySync
```
Thanks.

**Comment by boredazfcuk** [comment]
I say this, but I've just realise that a load of people are having issues with shared libraries so I'm going to have to pull this feature until the issues can be resolved

**Comment by leonardpitzu** [comment]
Many thanks!

**Comment by boredazfcuk** [comment]
I will be releasing two, I just need to work out how get my auto-build process to tag the second container as boredazfcuk/icloudpd:testing

**Comment by boredazfcuk** [comment]
That's done now. Your should be able to re-create your container from boredazfcuk/icloudpd:testing and it will have the iOS 16 shared library patches applied.

**Comment by epheterson** [comment]
Is this functionality ever going to move back to the main container? I just tried (thought I read somewhere that it was moved over) but it doesn't work without testing branch still.

**Comment by boredazfcuk** [comment]
Unknown. I made this container by merging a pull request into the base code of an upstream package. That upstream package rejected the pull request themselves and have since moved on. If the original author decides to re-base their changes to the latest version of the code, make the requested changes that the upstream package authors requested, and re-submit the pull request, then I'll be able to re-add it in.

**Comment by apriliars3** [comment]
> Many thanks for the Information! Don’t pull it - once you figure out how it works it’s great. Basically you need one container for the shared library and one for your local library, pretty simple. I guess a documentation update is all that is needed.

I tried, but docker with boredazfcuk/icloudpd:testing say me that my user is bad or incorrect password, I am using the same user and password on iCloud and the same docker with boredazfcuk/icloudpd:latest.

I create two dockers, icloudpd works, and then icloudpd_share don´t works for password and I have error keyring.

**Comment by boredazfcuk** [comment]
boredazfcuk:testing? There's your problem. No chance that works anymore.

I haven't pushed test builds to Dockerhub in a long, long time. They all go to a local, private repository now, as it's loads faster that way.

**Comment by apriliars3** [comment]
> boredazfcuk:testing? There's your problem. No chance that works anymore.
> 
> I haven't pushed test builds to Dockerhub in a long, long time. They all go to a local, private repository now, as it's loads faster that way.

So, is it possible to sync photos on iCloud shared folders with icloudpd:latest?

I have only synchronize the personal folder.

With the iCloud app in Windows 11 I can download both photos on shared and personal folders, and then transfer them to Synology Photos, but I want to save that step.

**Comment by boredazfcuk** [comment]
> So, is it possible to sync photos on iCloud shared folders with icloudpd:latest?

Yeah, once I finished the testing (of the shared libraries feature) I rolled the code into the main container.

Apple then made a change to authentication which broke everything and prevented the container from connecting. That was fixed in the main container, but as I have no need for the testing container, the fix was never rolled into that one. I guess I oughta delete it really

> I have only synchronize the personal folder.

> With the iCloud app in Windows 11 I can download both photos on shared and personal folders, and then transfer them to Synology Photos, but I want to save that step.

I used to have the icloud control panel on my windows laptop, but it just stopped working a couple of times and I only fixed it by reinstalling Windows. Also, I could only sync one user per windows user, so would have to keep logging off/on as different accounts to backup all the family photos. I backup 4 Apple IDs at the moment and created a 5th one today which will start being backed up in the next week or so. Bit of a nightmare any other way really.
