### ISSUE TITLE
Nothing happens after message : "Generating list of files in iCloud. This may take a long time"

### ISSUE THREAD

**Issue by JinhanM** [boredazfcuk/docker-icloudpd#272]
Hi there,
  I encountered a problem that I get everything correct, and nothing is downloaded or processed after a long time(over 12 hours). Has anyone encountered the same problem? Is there any thing I can do to debug this problem?

  My last log is:
<img width="1226" alt="截屏2023-01-29 19 14 29" src="https://user-images.githubusercontent.com/35931491/215322370-2aaa5ace-e49b-4646-8ab8-9d68747d291e.png">

Please help. Thanks a lot

**Comment by JinhanM** [comment]
btw, I think the problem is like this:
  Nothing happens when logging generating list of files, but when I terminate this I got message as below
<img width="1221" alt="截屏2023-01-29 19 18 34" src="https://user-images.githubusercontent.com/35931491/215322594-af2f0e95-8c5d-48fa-89d7-1cb44b71f9d4.png">

I entered 2FA twice when I initialise the shell. I thought generating list of files in iCloud means that everything has been set up.

**Comment by AlexaAmaya** [comment]
just....wait?

**Comment by AlexaAmaya** [comment]
same error of us, i am also looking for a solution to fix that :-(

**Comment by boredazfcuk** [comment]
Try re-creating your container but adding the variable `skip_check=True`.

This will just perform a download each time, which can be better if you have a large library.

Also, run `docker exec -it icloudpd sync-icloud.sh --RemoveKeyring` to remove your password, then try `docker exec -it icloudpd sync-icloud.sh --Initialise` to do your 2FA authentication again. You may be getting prompted because your password is incorrect.

Please be aware that there is an issue which is preventing users in China from authenticating correctly. This issue isn't fully understood at the moment, because it doesn't affect everyone.

Apparently it can be worked around by stopping my container, starting up a container from someone else whose amended the authentication component to work with iCloud in China, then swapping back to my container. The details should be in one of the recent Issues in this repo.

**Comment by boredazfcuk** [comment]
Closing as there's been no response in months... Presume this is resolved with previous comment.
