### ISSUE TITLE
Thoughts on synchronization_interval

### ISSUE THREAD

**Issue by li1220** [boredazfcuk/docker-icloudpd#279]
It is recommended to customize the synchronization_interval because I like to synchronize every 1 hour or set a fixed time, for example, to synchronize every hour

**Comment by boredazfcuk** [comment]
Apple enforces rate limiting and blocks accounts which synchronise too frequently. The synchronisation_interval variable exists because it gives people a choice of acceptable values which are less likely to see them blocked. It will still happen from time to time however, as people may restart their containers too frequently.

There is a variable which will exit after a single run. You can use this to start the container as frequently as you want. Details are in the README.
