### ISSUE TITLE
Use of app specific passwords

### ISSUE THREAD

**Issue by Monkyyy** [boredazfcuk/docker-icloudpd#288]
Is there a way to use app specific passwords? I use yubikeys for the 2FA/FIDO stuff on my Apple ID so there is no way to use this.
I've tried to use authentication_type=Web but it asks for an 2FA via SMS or Pop Up on an device.

Until I switched to the Yubikeys every thing works fine. Thanks for that nice project - good work :)

**Comment by AndreyNikiforov** [comment]
> Is there a way to use app specific passwords?

If you create app specific password and it works on icloud.com, then it most likely would work in icloudpd. Can you try it?

**Comment by Monkyyy** [comment]
> > Is there a way to use app specific passwords?
> 
> If you create app specific password and it works on icloud.com, then it most likely would work in icloudpd. Can you try it?
On icloud.com it neither has worked but according to https://github.com/picklepete/pyicloud/issues/349 I guess its a "problem" by pyicloud.

**Comment by AndreyNikiforov** [comment]
> On icloud.com it neither has worked but according to https://github.com/picklepete/pyicloud/issues/349 I guess its a "problem" by pyicloud.

pyicloud and, consequently, icloudpd, emulate web access to icloud.com - there is no special iCloudAPI that Apple exposes. If app-specific passwords work on icloud.com, they should work in pyicloud & icloudpd. Since you confirmed that app-specific password does not work for icloud.com, then nothing can be done in open source project to make it happen -- it is Apple limitation of app-specific passwords.

**Comment by boredazfcuk** [comment]
"App-specific passwords" are for use with Apps that run on iDevices. They cannot be used to log in to icloud.com because Apple does not allow it.
