### ISSUE TITLE
IOError while writing file to /iCloud/2023/02/IMG_6269_HEVC.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...

### ISSUE THREAD

**Issue by Arnold4869** [boredazfcuk/docker-icloudpd#319]
有人遇到这个问题吗？
我之前是用的pjoc的镜像。修改了两个文件，live photo 下载后的视频文件不带_HEVC.
现在换回官方镜像，遇到提示下载 liver photo 的视频文件就报错。IO 报错。
本来想修改官方的那两个文件也让下载的文件名不带_HEVC，但好像文件变化挺大的，不知道怎么改了。

**Comment by Arnold4869** [comment]
是icloud文件夹下的子文件夹的权限和所有者没设置好，我以为设置好了，实际没，重新在群晖下更新了就好了

**Comment by ben4562002** [comment]
謝謝 Arnold，我今天也遇到一樣的問題，把 iCloud 資料夾的權限設定允許寫入就可以了

**Comment by jinnxu75** [comment]
> 

我所有的文件都写不进去。报这个错误，但是我看了权限也没问题啊。
你是把iCloud文件的哪个用户权限要设置为可以写入？我看了我的用户，和Administrator都是有写权限的。

**Comment by LeezPayne** [comment]
Errors such as the host machine storage folder being unreadable or encountering "file too large" issues are often caused by Docker's insufficient read and write permissions on the host's "/iCloud" folder. If you are deploying icloudpd using Docker within a Synology DiskStation (群辉), it's necessary to grant read and write permissions to the "System" user group for the host's "/iCloud" folder using FileStation.

Alternatively, you can resolve this issue by modifying the permissions of the "iCloud" folder using a command. However, this approach grants broader permissions and may override some of the original permissions settings on the Synology DiskStation, making it less recommended:
`chmod 777 path/to/iCloud`
Pay careful attention to the provided path. Some issues mentioned the "755" permission，which might not be suitable for the Synology DSM, as it only grant write access to the owner and not to other users.
