### ISSUE TITLE
Operation Not permitted

### ISSUE THREAD

**Issue by yhiji1** [boredazfcuk/docker-icloudpd#328]
Ive been struggling for like an entire day to get this working lol. Most of the time I've been trying  in truenas, using both custom app and just deploying a docker container through the GUI. 

The first ever time I tried it everything went through fine until it was time to download the photos, where I would get IOError and it wouuldnt download.  Now everytime I try it this is the only thing i get.

Ive done it a bunch of times on truenas, and the latest time i tried running it on portainer and mounting the truenas samba shares to store the photos and it still didnt work. that suggests it might be something with truenas but I wanted to know if anyone else here has ran into something similar. 

thank you

![Screenshot 2023-04-26 003207](https://user-images.githubusercontent.com/131002872/234471049-0830cbbb-1c30-4967-8bad-588ac0c64455.png)

**Comment by boredazfcuk** [comment]
Hi,

Sorry for the short message. I was on GitHub mobile this morning and in a bit of a rush.

I believe that the issue is due to the container not being run in privileged mode... I'm not entirely sure why, but some systems require this. I've noticed this on Raspberry Pi devices and NAS devices. I believe it's something to do with the version of libseccomp2 which runs on the host machine. Older versions require `--privileged`, where newer version do not, I believe.

Some dude's done a really nice YouTube video on how to configure it in on a TrueNAS Scale device. It will be the top hit if you search YouTube for N6I3m-skRLw

Thanks.

**Comment by yhiji1** [comment]
Thank you for your detailed response! I've seen the other issues like this and have tried running them in privileged mode through truenas and portainer, to still the same issue. I've seen the video and followed but still get the same issue. Im not sure if it's something with share permissions of the datasets on truenas, but he does not go over that on video. 


However I'm definitely not super experienced with any of this so I'll try again soon and get back to you. thank you again.

**Comment by yhiji1** [comment]
Okay i found the issue, seems like when setting permissions via truenas GUI either i wasnt doing something right or it just wasnt working, but when setting permissions in the CLI it worked. thank you again
