### ISSUE TITLE
Some User Experience Tips//一些使用体验

### ISSUE THREAD

**Issue by AlexaAmaya** [boredazfcuk/docker-icloudpd#336]
Some User Experience Tips

1. Use the latest version (if you previously didn't delete it completely, it might cause some trouble).
2. For Chinese users, pay attention to two values in icloudpd.conf file - `auth_china=true; icloud_china=true` (there used to be a problem, but the author fixed it).
3. Especially pay attention to the time zone settings. In the previous version, it used the expression `CST-8`, but the author updated it to use the standard from [https://timezonedb.com/time-zones](https://timezonedb.com/time-zones). Chinese users please note to use `Asia/Shanghai`

一些使用体验

1. 使用最新版本（之前没有删除彻底，在这里折腾了很久）
2. 对于中国用户，留意icloudpd.conf文件的两个值——auth_china=true；icloud_china=true （原来似乎有问题，但是作者fixed了）
3. 尤其留意时区的设置，在原先的版本中，使用的是CST-8这种表述，但作者又更新了，目前使用的是[https://timezonedb.com/time-zones](https://timezonedb.com/time-zones)的标准。中国用户请注意，使用`Asia/Shanghai`

**Comment by boredazfcuk** [comment]
I'm closing this off as it's not really an issue, but I've stickied it, just in case.

**Comment by chewenkai** [comment]
Really helpful, thanks.

**Comment by latel** [comment]
Really helpful, thanks.
set to china solves the problem https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/804

**Comment by hybnew** [comment]
I got an error after i run the init script, when i input password, it reports "Bad username or password". 
The env is Synology NAS ContainerManager.
While I try it on my personal Mac, it succeed.
Then I read the configuration document again, found that **I neglected to configure the bridge network for docker!!!!**. That's why i got an error forever. If you run this images on your Synology NAS as well,  make sure create your network and container manual or run with ContainerManager UI and configure network.
