### ISSUE TITLE
Download failing : mess in parameters in conf file

### ISSUE THREAD

**Issue by caplam** [boredazfcuk/docker-icloudpd#344]
I can't download photos.
At first i had not set any parameters for folder structure and it downloaded all my photos in /homeUser/iCloud/all
Then i used folder structure={album} and photo album="all albums" : result nothing downloaded and a call trace
Next i used folder structure={album} and photo album="all albums" and skip_albums= "All Photos,Time-lapse,Videos,Slo-mo,Bursts,Panoramas,Screenshots,Live,Recently Deleted" : result it downloaded Video and Time Lapse

[icloudpd.txt](https://github.com/boredazfcuk/docker-icloudpd/files/11612373/icloudpd.txt)
[log.txt](https://github.com/boredazfcuk/docker-icloudpd/files/11612357/log.txt)

You can see command line is not generated accordingly to conf file parameters. It seems there is a mess between folder strucuture, photo_albums and skip_album.

edit : replaced pasted text with files as it's more readable.

edit2: seems a bit different with the rest of the log.  [log1.txt](https://github.com/boredazfcuk/docker-icloudpd/files/11614948/log1.txt)
Albums nested in folders are not downloaded
To end up the only albums downloaded are Video and Time Lapse (which are in skip album

When you look at generated command line it seems there is a bug, for example:
iCloudPD launch command: icloudpd --directory /home/user/iCloud --cookie-directory /config --domain com --username XXXXXXXXXXXXXXX --folder-structure Événements iPhoto --album Événements iPhoto 2>/tmp/icloudpd/icloudpd_download_error

folder-structure and album are the same and the value of these parameters should be for skip album.

Two lines seem strange to me in sync-icloud.sh
156:    older_structure="${folder_structure}"

1436: folder_structure="${older_structure}"
but i've almost no knowledge in coding

**Comment by boredazfcuk** [comment]
The **folder_structure** variable should be set to something like %Y/%M/%D.

When downloading albums though, I temporarily change the value of **folder_structure** to be the same as the album name. This way the files on disk will look like something like this:

/home/user/iCloud/Album1
/home/user/iCloud/Album2
/home/user/iCloud/Album3

So that I don't lose the original value of the **folder_structure** variable, I copy it to another variable called **older_structure**, because it's the older value for **folder_structure**. Once I've finished downloading the albums, I set the **folder_structure** variable back to what it was previously.
