### ISSUE TITLE
How to add a shared library?

### ISSUE THREAD

**Issue by blackfox33** [boredazfcuk/docker-icloudpd#345]
In the container variables I can set 
`photo_library:` Set this to the name of an iOS 16 shared library to only download photos from a single shared library.
How can I get the variable name of my shared library?
`docker exec -it icloudpd /usr/local/bin/sync-icloud.sh --list-libraries` did not give me any output
`Ignoring invalid launch parameter specified: --list-libraries` was the warning message.

**Comment by boredazfcuk** [comment]
That should be commented out as it is not supported. I tried to get it working in the testing branch, as someone submitted a PR request, which I integrated. That PR broke the container for a lot of people, so I moved that functionality out to boredafcuk/icloudpd:testing

The PR was never fixed, and the base code has moved on a ling way since then, so unless the original author decides to rebase and fix their patch, I'll not be able to add it back into the latest container.
