### ISSUE TITLE
Recently Deleted Scan not taking into account Duplicates removed using iOS

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#371]
I believe there is a bug with how the delete option works in this program.

iOS has a remove duplicates option, where it will delete one copy of the duplicated file. Moving one to Recently Deleted and keeping the other in the Library.

The delete option of this program scans Recently Deleted and then deletes the downloaded file. Normally, this is okay. But in this instance there are both Library versions and Deleted versions of the file.

Can you add functionality to ensure a Recently Deleted File that also exists in the Library is not deleted when a new scan is conducted?

I hope the above makes sense.

**Comment by boredazfcuk** [comment]
It's not a bug, it's just the nature of the utility due to the differences in how photos are are stored.

Apple device use a database to index and keep track of your photos. This allows for multiple files with the same name/size/date.
This utility uses a file system to store copies of your files, so it cannot store two files of the same name/size/date.

To get around this, it will use the date of the file to place it in its own folder (requiring the use of the **folder_structure** variable). If two files have the same name and date then it will check the file size, and append an tag to the file name, so they can be differentiated.

However, when two files are truly duplicates, the utility has no way of storing them in different locations because the files are identical.

The best way to handle duplicates is just to remove them from your 'Recently Deleted' folder. This way it won't sync the delete and the original file will remain, or if it already processed the delete, it will just re-download the file on the next run.

**Comment by boredazfcuk** [comment]
> So even tho the utility states the file already exists when it syncs, then checks for deleted items after. There is no way for you to index the duplicate file that’s deleted so it checks if it was already scanned and identified?

No, it doesn't know "the" file exits, just "a" file exists.

When you save a photo to an idevice (whether via a camera, or downloaded, or saved from an app) it will give that file a unique ID number and replicate the file across all devices using that ID. It doesn't care what the file is named, every single photo could be called cat.jpg and it would be fine with that.

When you log on to iCloud.com however, all files are presented by name and there is no unique reference for each file. Having them all called cat.jpg suddenly becomes a problem.

As the files are no longer uniquely identifiable, icloudpd had to come up with a way reduce the possibility of it missing files. It does this by checking to see if a file of the same name exists in the download folder already. If it does, it takes the last 5 (or maybe 6, I can't recall off top of my head) digits of the file's size, and appends it to the file name eg cat-27437.jpg. If you had two files with the same name, and coincidentally, the same 5 or 6 digits for the size, icloudpd would consider these files to be the same, and not download the second file. This doesn't mean they are identical, just that they are as per icloudpd's best guess.

To reduce the number of duplicates, you can make **folder_structure** more fine grained. Have it set to 'none' and it's highly likely you'll have plenty of duplicates. Set it to %Y and there will be less, for maximum effect, set it to %Y/%M/%D as it would be extremely unlikely to have two different files, of the same size, with the same name, created on the same day.

> the only way I see around this is to switch off the container. Run my duplicate delete in iOS, purge recently deleted, then switch back on.

This is pretty much how I get rid of duplicates. I find some apps will call their files exactly the same name when you save them. I just make sure to delete any that are having issues from 'Recently Deleted' on my handset and leave it to tidy up on the next sync.

> I’ve just recently completed a full backlog sync of my entire photos across multiple devices and storage locations. Over 100k files. iOS has identified over 4k exact duplicates.

Could be worthwhile removing the dupes before syncing the photo library next time. Will save a fair bit of bandwidth.

> Your service has enabled me to do a full download of iCloud “as is” to create a backup in one place. But the duplicates will delete 4k+ copies, and move them to recently deleted. Leaving the service switched on, it will then delete the same files even tho a copy exists in the library.

Yes, but then it will download the files again the next time a sync occurs because they still exist in the library, then delete the files because they still exit in 'Recently Deleted', the re-download the files... etc.

> Unless, the next scan will pick up the remaining duplicate still in the library and then redownload it.

Yep

> Apologies for the thought process of the reply, was more thinking out loud. But the last point is a good theory, will it redownload the remaining duplicate if I’ve purged recently deleted? Surely it would…

Yeah, it just replicates whatever is found on iCloud.com. If it's still there, it will download it again.

It is a bit annoying when files get caught in the download/delete cycle, but just needs them removing from 'Recently Deleted' to sort. I'm kinda lucky as I don't see anywhere near that many. I don't even have 4K photos in my library as I upload them all to a Nextcloud server, then remove from my phone... the Mrs, however, has has a crazy amount of photos. I just give up and pay Apple for more storage for that 😂

**Comment by AndreyNikiforov** [comment]
There may be a way to make icloudpd smarter about dups. We have access to asset ID from the icloud and I assume, we should be able to identify what assets to download and which to delete, even if they are dups using name-size criteria. I need to try icloud API with setup for dups to see if we'll be able to differentiate...

**Comment by gxander85** [comment]
Thank you for the responses!

> To reduce the number of duplicates, you can make **folder_structure** more fine grained. Have it set to 'none' and it's highly likely you'll have plenty of duplicates. Set it to %Y and there will be less, for maximum effect, set it to %Y/%M/%D as it would be extremely unlikely to have two different files, of the same size, with the same name, created on the same day.

Yes, I have set the structure to be {:%Y/%Y-%m/%Y-%m-%d}. So the duplicates it is identifying are 100% exact matches.

> Could be worthwhile removing the dupes before syncing the photo library next time. Will save a fair bit of bandwidth.

This I might do over the weekend. Clear them out and maybe start fresh with a rebuilt container.

> Yes, but then it will download the files again the next time a sync occurs because they still exist in the library, then delete the files because they still exit in 'Recently Deleted', the re-download the files... etc.

Can confirm the file was re-downloaded today on the next scan. At least this is a "fail safe" for the deletion of duplicates from within iOS. Just have to remember to also purge them from recently deleted.

> It is a bit annoying when files get caught in the download/delete cycle, but just needs them removing from 'Recently Deleted' to sort. I'm kinda lucky as I don't see anywhere near that many. I don't even have 4K photos in my library as I upload them all to a Nextcloud server, then remove from my phone... the Mrs, however, has has a crazy amount of photos. I just give up and pay Apple for more storage for that 😂

As a photographer (and data hoarder), it is just easier for me to have 2TB iCloud and sync across all my Apple devices. But as iCloud is not a backup service, your system fills a hole I desperately needed. It is a fantastic program. Just working thru the quirks.

**Comment by gxander85** [comment]
> There may be a way to make icloudpd smarter about dups. We have access to asset ID from the icloud and I assume, we should be able to identify what assets to download and which to delete, even if they are dups using name-size criteria. I need to try icloud API with setup for dups to see if we'll be able to differentiate...

This would be fantastic and something you should definitely explore. For now tho, the work around fixes will do okay.
