### ISSUE TITLE
auto_delete: "True" not deleting files

### ISSUE THREAD

**Issue by robflate** [boredazfcuk/docker-icloudpd#41]
I have `auto_delete: "True"` enabled and the logs show;

```
Deleting any files found in 'Recently Deleted'...
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0047.JPG!
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0037.JPG!
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0041.JPG!
today at 13:08 2020-11-13 13:08:48 INFO     New files downloaded: 1
today at 13:08 2020-11-13 13:08:48 INFO     Sending Telegram downloaded files notification
today at 13:08 2020-11-13 13:08:48 INFO     Telegram downloaded files notification sent successfully
today at 13:08 2020-11-13 13:08:48 INFO     Number of files deleted: 14
today at 13:08 2020-11-13 13:08:48 INFO     Sending Telegram deleted files notification
today at 13:08 2020-11-13 13:08:48 INFO     Telegram deleted files notification sent successfully
today at 13:08 2020-11-13 13:08:48 INFO     Synchronisation complete for robmint
```
but when I check the filesystem, the files are not deleted and have different names with a string appended to the end;

```
IMG_0047-973486.JPG
IMG_0037-978773.JPG
IMG_0041-974132.JPG
```
There are no other files in the folder that share the same name (i.e. `IMG_0047.JPG`, `IMG_0037.JPG` or `IMG_0041.JPG`).

Is it icloudpd that's renaming the files? If so, how can I ensure Recently Deleted files actually get deleted.

Thanks.

**Comment by boredazfcuk** [comment]
Hi,

I can see from the log that it has deleted the files:
```
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0047.JPG!
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0037.JPG!
today at 13:08 2020-11-13 13:08:47 INFO     Deleting /home/robmint/iCloud/2020/IMG_0041.JPG!
```

However, the leftover files you can see are due to photo de-duplication. The problem is that iCloud.com allows files with duplicate filenames. This means that there will be two files named IMG_0047.JPG, IMG_0037.JPG and IMG_0041.JPG in your iCloud.com storage.

When the script attempts to download the second files IMG_0047.JPG, IMG_0037.JPG and IMG_0041.JPG, it detects the duplicate filenames and appends the size of the file to the end of the name to de-duplicate.

**Comment by robflate** [comment]
Thanks...so is there a way to actually delete files in iCloud and have the script also delete them locally? The files icloudpd has renamed are the same files I deleted rather than a different file with the same filename.

**Comment by boredazfcuk** [comment]
It's just the way it is at the moment. There's a bug open in an upstream project for 'Smart deleting': https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/196

It's a bit of an issue because there can be two identically named files on iCloud, one being in an album, the other being in 'Recently Deleted' but the script has no current way of distinguishing between them.

Hopefully it will be amended to remove these de-duplicated files too.

**Comment by robflate** [comment]
Thanks for the link. From reading the thread, it suggests the problem happens when you have 2 identical files with the same name, metadata etc rather than just the same filename. Usually as a result of copying the file at some point. What's happening to me is;

1. Take a photo on iPhone and it uploads to iCloud.
2. Delete the photo from iCloud without doing anything with it. I don't edit it, copy it, add it to an album. Nothing.
3. icloudpd deletes the photo locally and then downloads it again appending the string to the end of the filename.

A quick checks shows I have 8 files in iCloud called `IMG_0047.JPG` but none are duplicates of the same file.

Does it sound like my issue is the result of the Smart deleting or could it actually be something else?

Thanks again for your time.

**Comment by boredazfcuk** [comment]
I just linked it to show that there are issues surrounding file deletion. There was another issue opened where they suggested doing the deletion prior to downloading, but that was closed without resolution:

https://github.com/icloud-photos-downloader/icloud_photos_downloader/pull/182

**Comment by robflate** [comment]
Thanks. I'll keep my eye on the issues upstream.

**Comment by boredazfcuk** [comment]
Okey doke. I have e-mail notifications enabled for the repo so I see all new issues, comments etc. and I do keep my container fairly up to date. I do like to run new versions on my home server for a day or two before I push new containers to Dockerhub. If any new changes are made around deletion, I'll merge them fairly quickly.
