### ISSUE TITLE
Suggestion: Replace ❌ with 🚮

### ISSUE THREAD

**Issue by luc-ass** [boredazfcuk/docker-icloudpd#421]
Hey there! First of all thank you so much for this container. Great work!

I wanted to suggest, that we replace the ❌ with 🚮, so that notifications don't look like an error occurred. For my taste the ❌ has quite a strong warning character, while 🚮 represents what actually happens. I'd happily create a pull request.

What are your thoughts on that?

**Comment by boredazfcuk** [comment]
I used the ⚠️ and 🚩 for warnings (IIRC). I picked the ❌ character because it's nice and vibrant so easily distinguishable at a quick glance.

The ones I don't like are ⏬ and ▶️ as I find them a bit plain. I'd rather replace those ones with something that stands out more, but there's nothing that really represents the actions being taken better than those two. I hope future updates to the emoji icon set allow me to choose the colours.

**Comment by luc-ass** [comment]
Thanks for your reply, I get that. It's obviously a matter of taste, what you expect from those notifications. Perhaps a better way would be to implement templates or something like that... I'll think about that a little more.

**Comment by boredazfcuk** [comment]
Yeah, a templates type thing would be good... `icon_set=default` and `icon_set=alternate` or something like that.

Then they'd set something like:
```
icon_start='\x123\blah'
icon_warning='\x123\blah'
icon_error='\x123\blah'
icon_download='\x123\blah'
icon_delete='\x123\blah'
```

**Comment by boredazfcuk** [comment]
Closed as no response in over a month
