### ISSUE TITLE
Feature request - Schedule by time of the day

### ISSUE THREAD

**Issue by BuSHari** [boredazfcuk/docker-icloudpd#43]
Hi,

It will be great if there will be another option to schedule by time of the day instead of intervals (like cron for example).
I have couple of accounts that i want to sync, and i don't want them to correspond.

Thanks...

**Comment by boredazfcuk** [comment]
I currently sync 3 accounts and hitting the server at the same time doesn't cause any issues. Apple won't block accounts for multiple concurrent logins to different addresses from the same account, or anything like that.

Originally the script used to run via cron, but I had issues with it. I can't quite remember what they were, as it was a good while ago, it was either issues around running as the correct user (cron was launching as root (instead of the user you configure) or it was due to cron launches not logging anything to screen.

I have appeared to stumble across an issue recently around synchronisation however. It seems Apple only lets people log in 26 times before they force 2FA re-authentication... When the interval is set to 60mins, you have to re-authenticate once a day which is a pain. Setting it to every 15mins will mean you have to re-authenticate multiple times a day.

I may put in a `synchronisation_delay` so that the first synchronisation can be delayed for 10/40/60/120/whatever minutes as a quick fix. I can also look at only accepting certain values for `synchronisation_interval` so that it can only be run a maximum of once every 6 hours... Any invalid time periods will default once a day or something.

Hopefully I'll get time to look at it tonight.

**Comment by boredazfcuk** [comment]
I've added `synchronisation_delay` to the new version so that you can offset the download by up to 60 minutes.

**Comment by BuSHari** [comment]
Great! thanks...

**Comment by boredazfcuk** [comment]
Just closing this off. Any problems, or suggestions, just reopen the issue.
