### ISSUE TITLE
"User name, user, already in use - exiting" error in log

### ISSUE THREAD

**Issue by jmaliakal** [boredazfcuk/docker-icloudpd#433]
I was running into the error "User name, user, already in use - exiting" after I configured my `user_id` to the user id for the username on my synology NAS (using the same user id value shown when running the `id` bash command - 1026)

I'm using the default `user` value of user, as I didn't see a line for this in the icloudpd.conf file created at the initial container startup.

After returning the `user_id` value to 1000 and chmoding the permissions of my download folder to 777, it seems to be working and downloading photos from icloud; however, I feel like this isn't the _correct_ way to do things.

Do I need to change the config of the container to user the correct user account and user id? If so, how can I do this?

**Comment by boredazfcuk** [comment]
The container creates the user account when it first launches.

If you leave it as default, it will create the user `user` with the user id `1000`.

The next time it launches, it will see that the user account `user:1000` already exists and skip user account creation.

If you then change the settings to `user=user` and `user_id=1026` the container will not find the user account `user:1026` and attempt to create it. This is where your problem lies, the account `user` already exists with id `1000` so a second account named `user` cannot be created.

If you want to force the container to `user:1026`, just delete the container and re-create it. It will then create the `user:1026` account on first run.

**Comment by boredazfcuk** [comment]
Closing as no response in over a month.
