### ISSUE TITLE
iCloud auth error

### ISSUE THREAD

**Issue by theikid** [boredazfcuk/docker-icloudpd#476]
Hi there, there's a bug in the iCloudpdt scrip that prevent from connecting to iCloud account. See it here discussed : https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/729

Apparently there's a new update fixing it, would it be possible to update the docker image to that version ? 

edit: I've seen the merge-request and topic About this. Truecharts told me they are using latest version from upstream but it doesn't seem it has the fix.

**Comment by boredazfcuk** [comment]
This issue was fixed in icloudpd v1.17.0 which was incorporated into the Docker image about two weeks ago... Since then I've also released containers with v1.17.1 and v1.17.2.

I've just this moment published yet another a new version which bring it up to the latest version, v1.17.3, which was released on the 3rd January. The release notes say that it improves compatibility for different platforms. I'm not sure if it will fix the issue that you are seeing, but even if it does, it seems that Truecharts is lagging behind quite a bit and not using the latest version as claimed.
