### ISSUE TITLE
.HEIC to .JPG; is it smart enough to know not to redownload every time?

### ISSUE THREAD

**Issue by 0949er** [boredazfcuk/docker-icloudpd#48]
I do not have the "convert_heic_to_jpeg" flag set and manually converted one of the .HEIC files to .JPG to see if on a re-sync it would re-download the original .HEIC and it did.

My guestion is if I set the "convert_heic_to_jpeg" flag to "True" will it be smart enough to check existing files against the .JPG name (instead of the .HEIC name) and not download every time?

Also, can I manually convert all my existing .HEIC files to .JPG and move on from here with the "convert_heic_to_jpeg" flag or should I let the program do it?

**Comment by boredazfcuk** [comment]
Hi,

My Docker container is not much more that a wrapper for the icloud_photos_downloader: https://github.com/icloud-photos-downloader/icloud_photos_downloader

Unfortunately, icloud_photos_downloader does not natively support HEIC to JPG conversion, so it if it finds a HEIC file that does not exist, it will download it.

If you want to convert all your HEIC files to JPEG, connect to your container with `docker exec -it <containername> /bin/ash` and then run `/usr/local/bin/sync-icloud.sh --ConvertAllHEICs`

The **convert_heic_to_jpeg** variable only converts files going forward from the time it was set.

**Comment by 0949er** [comment]
boredazfuck, 

Again thankyou for your input.

So I have a 3rd party software that can convert HEIC to JPG with no issues. What I "want" to do is convert every existing .HEIC back to .JPG in my thousands of files and then delete the *.HEIC version out of my download directory but what I believe you are saying is that when the container re-runs it will see all the missing *.HEIC files and pull them back down? 

So when people use convert_heic_to_jpeg are they usually keeping BOTH files on hand if they are continually trying to grab current photots?

Thanks,

**Comment by boredazfcuk** [comment]
>what I believe you are saying is that when the container re-runs it will see all the missing *.HEIC files and pull them back down?
That's correct, the Python script that's invoked just looks to see what is on iCloud.com, and if there is no matching HEIC file already in the destination directory, it triggers a download.

> So when people use convert_heic_to_jpeg are they usually keeping BOTH files on hand if they are continually trying to grab current photots?

Yes, that's what I currently do. Converting to JPEG is a lossy process so the files are lower quality and they're also considerably larger than the equavalent HEIC file. Admittedly, quality wise, it's probably as near as makes no difference.

My primary device is a Windows 10 based laptop so, which doesn't natively support HEIC. This is my only reason for converting to JPEG... so that I can actually browse my photo collection. Once Windows 10 supports HEIC natively, or I can install an application I trust which supports HEIC properly, then I'll remove all the JPEG files and switch off HEIC conversion in my container.

**Comment by 0949er** [comment]
> > what I believe you are saying is that when the container re-runs it will see all the missing *.HEIC files and pull them back down?
> > That's correct, the Python script that's invoked just looks to see what is on iCloud.com, and if there is no matching HEIC file already in the destination directory, it triggers a download.
> 
> > So when people use convert_heic_to_jpeg are they usually keeping BOTH files on hand if they are continually trying to grab current photots?
> 
> Yes, that's what I currently do. Converting to JPEG is a lossy process so the files are lower quality and they're also considerably larger than the equavalent HEIC file. Admittedly, quality wise, it's probably as near as makes no difference.
> 
> My primary device is a Windows 10 based laptop so, which doesn't natively support HEIC. This is my only reason for converting to JPEG... so that I can actually browse my photo collection. Once Windows 10 supports HEIC natively, or I can install an application I trust which supports HEIC properly, then I'll remove all the JPEG files and switch off HEIC conversion in my container.

boredazfcuk, 

What version of windows 10 do you run? I run Windows 10 Pro 1909 and it does natively support .HEIC file formats. This is true for both my home and work computers.

The reason I am trying to figure this out is because my main use PC at the house runs Kubuntu and (as far as I can tell) the dolphin file browser does not support .HEIC so I simply want to see the thumbnails when going through the files. I dont want to download .HEIC and .JPG because I run a file server for backup which also replicates in the cloud and I would effectively double my storage costs.

Anyways thanks again for your help. If you could just work with Apple to get that 2FA token to NOT expire after 26 tries that would be great :) Take care my friend.

**Comment by boredazfcuk** [comment]
I'm running the latest Win10 Pro 20H2 which is the version which was just released in October... I've had the HEIF Extensions installed through many different versions, probably since the 17xx or 18xx versions.

I thought I'd reset Windows just in case I had a corrupt install, but I'm back up and running and it's still the same. I don't see thumbnails in Windows Explorer and opening them in `Photos` gives me the old "We can't open this file" error.

>If you could just work with Apple to get that 2FA token to NOT expire after 26 tries that would be great

lol. I hope they change it too. I'm not sure they'll listen to me though!
