### ISSUE TITLE
Token expiring early/no renewal notice sent

### ISSUE THREAD

**Issue by ryan-adler** [boredazfcuk/docker-icloudpd#524]
I have noticed that my token seems to expire after (around?) 30 days, not 3 months, as stated in the configuration docs.  I only know that it has expired because I start to get notifications on my phone that I need to allow the login.  The container itself, though, does not realize that the token has expired, and hangs on:
`Fetching libraries list...`

**Comment by boredazfcuk** [comment]
So, my cookie expired today. Looks like Apple must have reduced the cookie timeout to 30-days after all. Thanks for bringing this to my attention.

**Comment by boredazfcuk** [comment]
I've changed the script so that it checks a different expiry date within the container. This will now recognise the 30-day timeout and send out notifications on day 21.

I've also added the capability to remotely re-authenticate using Telegram and also created a new reauth.sh script to quickly re-enter the MFA code from the container command line. See the CONFIGURATION.MD file for further details.
