### ISSUE TITLE
should we careful the photo is the correct orginal one?

### ISSUE THREAD

**Issue by 1123123w** [boredazfcuk/docker-icloudpd#600]
Recently, I changed the folder structure from {:%Y/} to {:%Y/%m}. When I used Duplicate Cleaner Pro to help me delete the duplicate photos (because some photos were already deleted from iCloud), I found out there were still a bunch of photos in the yearly folders. However, Duplicate Cleaner didn't recognize them because they were the same photos but with different MD5 checksums. I checked every single picture to find out why.

In the end, I discovered that some of them were damaged; there were some "color blocks" in parts of the photos or screen tearing.

Additionally, some large videos also failed to play because their sizes were only half of what they should have been.

so,my point is how can we avoid or how can we check the photo is excatly the same as icloud?

**Comment by 1123123w** [comment]
![example](https://github.com/boredazfcuk/docker-icloudpd/assets/9305326/1fec6a35-9a06-4513-b554-b9b782f488e7)
in case i dont speak clearly,here is the screenshot

**Comment by boredazfcuk** [comment]
I've seen this issue before and it's the result of cross-linked files. It's a filesystem issue rather than an icloudpd issue. It will occur when a drive is failing. Not much I can do about this. The photo would have been a perfect replica of what was in icloud at them time it was downloaded. Drive failure/corruption is what will have resulted in the difference. Only option is to restore from icloud/backup.
