### ISSUE TITLE
Sync does not start (ERROR: Valid cookie file has not appeared within 30 minutes. Restarting container...)

### ISSUE THREAD

**Issue by sachins06** [boredazfcuk/docker-icloudpd#609]
I have set up everything according to the documentation. The container starts, is able to find the .mounted file, and is also able to find the cookie file. However, I get an error message after 30 minutes stating "Valid cookie file has not appeared within 30 minutes. Restarting container...". I have checked the cookie file that is shown in the log file below and it does have proper permissions to be read.

Logs: https://pastebin.com/hciu2c45

**Comment by boredazfcuk** [comment]
When initialising a brand new container, you'll be prompted to confirm a multi factor authentication code twice. The first time, is when the authentication app connects to Apple servers to validate your password and save it to the system keyring. It will create a cookie at this point, but this cookie will not be valid for iCloud downloads.

You will then be prompted to confirm your multi factor authentication code a second time. This second time updates the cookie so that it allows you to also connect to the Photos service. At this point it will continue and download the photos.

If you fail to enter the correct multi factor authentication code on the second request, it will lead to the same situation as you describe.

Just delete the cookie and reinitialise the container. It will already have your password saved to the keychain, so should only ask for the multi factor authentication code once the second time around.

**Comment by sachins06** [comment]
I tried the steps you highlighted and I'm getting this error now:

2024-07-08 10:11:44 ERROR    Cookie is not multifactor authentication capable, authentication type may have changed
2024-07-08 10:11:44 ERROR    Invalid cookie file has been removed. Restarting container in 5 minutes

**Comment by boredazfcuk** [comment]
I've checked this in a brand new test container and it worked fine. Not sure where the problem lies and can't reproduce it.

**Comment by sachins06** [comment]
I figured it out. I had "Advanced Data Protection" turned on for my iCloud. Once I turned it off and re-initialized the iCloud connection, it started to work.

**Comment by boredazfcuk** [comment]
Thanks for the update

**Comment by petrich-lmjp** [comment]
Had the same situation. [This](https://github.com/boredazfcuk/docker-icloudpd/issues/609#issuecomment-2214781931) solved it and made the trick for me ! Thanks @boredazfcuk for continuous support.
