### ISSUE TITLE
iCloudPD is downloading and then deleting photos

### ISSUE THREAD

**Issue by schellbell** [boredazfcuk/docker-icloudpd#625]
I'm not sure how long this has been happening, as I only realized it once I setup a telegram notification for the status of the syncs. It seems like my container keeps downloading and then deleting the same 13 photos. They are all older photos that haven't had any changes to them (the newest photos is dated 2008). 
![image](https://github.com/user-attachments/assets/febd4ab6-25fe-45ed-b091-32988e406724)
I thought it was a weird single occurrence, but it has happened every time the container has performed the last 10 syncs.

**Comment by boredazfcuk** [comment]
This happens to me fairly often. I often save images from Signal/Telegram/etc to the phone, send them someone else, then delete it from my photo stream. That photo then stays in the `Recently Deleted` photo for 30 days.

I then save the same image from Signal/Telegram/etc again, to sent to someone different, but leave it in my photo stream.

I now have two photos with exactly the same name in iCloud. It downloads the photo because it's in my photo stream, then deletes it because it's also in my 'Recently Deleted' album too.

To get rid of it, I just remove the file from my photo stream and/or 'Recently Deleted'.
