### ISSUE TITLE
The JPG files are being downloaded repeatedly, even though the EXIF data and file size are the same.

### ISSUE THREAD

**Issue by pp-2** [boredazfcuk/docker-icloudpd#707]
2024/12/10 18:30:12	stdout	2024-12-10 18:30:12 INFO     Downloaded /iCloud/2024/06/13/IMG_0790-3738188.JPG
2024/12/10 18:30:12	stdout	2024-12-10 18:30:12 DEBUG    Setting EXIF timestamp for /iCloud/2024/06/13/IMG_0790-3738188.JPG: 2024-06-13 11:52:14+0800
2024/12/10 18:30:11	stdout	2024-12-10 18:30:11 DEBUG    Downloading /iCloud/2024/06/13/IMG_0790-3738188.JPG...
2024/12/10 18:30:11	stdout	2024-12-10 18:30:11 DEBUG    /iCloud/2024/06/13/IMG_0790-3738188.JPG deduplicated

The JPG files are being downloaded repeatedly, even though the EXIF data and file size are the same.

**Comment by boredazfcuk** [comment]
`2024/12/10 18:30:12 stdout 2024-12-10 18:30:12 DEBUG Setting EXIF timestamp for...`

Duplication is expected behaviour when setting the EXIF timestamp using **set_exif_datetime=true**. You are changing the local file, so icloudpd downloads a copy of the original. I'm sure this used to be mentioned in the configuration documentation, but doesn't seem to be there anymore, so I've added something to explain it again.
