### ISSUE TITLE
HEIC conversion of portrait oriented pics come out landscape

### ISSUE THREAD

**Issue by jon-small** [boredazfcuk/docker-icloudpd#98]
First of all, awesome software and it has been a saviour for all my frustration trying to get the iCloud for Windows working. I'm running it as a container on a QNAP NAS and is working brilliantly. Thank you!

I noticed a peculiarity that I'm not sure others have seen. I've used the HEIC conversion option and for any photos that are originally taken in a portrait orientation, the conversion works by converting them to a JPG, but it rotates it clockwise by 90 degrees into a landscape orientation. I sync'd about 10k photos, and it did this for every HEIC that was taken in a portait format.

Here's a properties comparison of 2 example files showing the vertical/horizontal dimensions are reversed after the conversion.

![Screenshot 2021-09-06 082554](https://user-images.githubusercontent.com/90040034/132238850-ef013c6d-6531-470a-b2d4-679c81b02f48.png)

Please let me know if you have any questions or need anything else to research the issue such as logs.

Thank you,
Jon

**Comment by boredazfcuk** [comment]
Hi,

I have looked into this before, but the issue is a discrepancy between Apple and non-Apple. Apple tags their photos with the correct orientation, so that it will be displayed correctly on their devices. Other formats ignore this metadata tag and just assume it's a certain way.

I see this on my own photos, because I use the volume button as the "take picture" button and have that in the top right when taking a photo. Apparently this is "upside down" as far as Apple is concerned. For some bizarre reason, they expect those buttons to be on the bottom edge when the photo is taken.

I'll have a look and see if I can find a way of getting the conversion utility to orientate the photo as per the metadata, or maybe using a different converter that respects it.

**Comment by boredazfcuk** [comment]
I've pushed out a new version which ditches the `heif-tools` packages and uses imagemagick instead. I removed all the files I have from this month and re-downloaded everything. The new conversion tool oriented the JPEGs the correct way or as Windows describes it: 'Normal'.

I've then added a command line option `--ForceConvertAllHEICs` which will go through all the HEIC files in the `/home/${user}/iCloud" qnd re-convert them, overwriting the current JPEGs. This will save time as you won't need to remove your library and re-download everything, it just runs the conversion process of the script.

Let me know how you get on. Thanks.

**Comment by bauzer714** [comment]
@boredazfcuk aside from improved landscape vs portrait handling, is there an observed quality or file size difference?

**Comment by boredazfcuk** [comment]
Possibly, but I didn't do any detailed testing.

Both utilities allowed setting the conversion quality via the command line using an integer number. The old package used to use a scale of 1-100, the Paint.NET Windows app also uses 1-100, so I presume ImageMagick uses 1-100, and not something daft like 1-255.

I set mine to 100, and the files are hitting 3-15MB in size, so there's not much compression going off there on the 'busy' photos at a guess.

**Comment by jon-small** [comment]
Okay, this works way better. It was odd that there were some stubborn JPGs that wouldn't convert, so I purged them and re-ran the  `--ForceConvertAllHEICs` and it successfully converted the HEICs. Thank you for addressing this so promptly and effectively!

**Comment by boredazfcuk** [comment]
No problems. I just need to somehow figure out how to retrospectively run this against the 20+GB of photos I've archived out of my iCloud photo stream. Wish me luck 😂
